const quotes = [
    "¡Hasta la vista, baby! - Terminator 2: Judgment Day",
    "Que la Fuerza te acompañe. - Star Wars",
    "Here's looking at you, kid. - Casablanca",
    "Mira, mamá, sin manos. - E.T. el extraterrestre",
    "¡A volar, juntos, hacia lo desconocido! - Titanic",
    "¡Eres un mago, Harry! - Harry Potter y la piedra filosofal",
    "Rosebud. - Ciudadano Kane",
    "Say 'hello' to my little friend! - Scarface",
    "Hakuna Matata. - El Rey León",
    "Yo soy tu padre. - Star Wars: El Imperio Contraataca",
    "¡Voy a hacerle una oferta que no podrá rechazar! - El Padrino",
    "Tienes una forma muy peculiar de ver las cosas. - El club de la pelea",
    "¡Que el juego empiece! - Saw",
    "Carpe diem. Aprovecha el día, chico. - El club de los poetas muertos",
    "¡Adiós, amigo! - Thelma y Louise",
    "To infinity and beyond! - Toy Story",
    "Mi precioso... - El Señor de los Anillos: La Comunidad del Anillo",
    "¡Eres un juguete! - Toy Story",
    "Louis, creo que este es el comienzo de una hermosa amistad. - Casablanca",
    "Puedes hacerlo. - Agua para elefantes",
    "¡A la caza! - Depredador",
    "La vida es bella. - La vida es bella",
    "Hazlo! - Star Wars: Episodio VI - El retorno del Jedi",
    "¡No te rindas! - Buscando a Nemo"
];